name = "viralab-web"
compatibility_date = "2026-09-18"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "viralab.space"
custom_domain = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"

[observability.logs]
enabled = true
head_sampling_rate = 1.0
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 0.10
persist = true
